spring:
  application:
    name: DDDSample
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    max-active: '10 # Maximum number of connections allowed in the pool'
    pool-size: '5  # Minimum number of idle connections in the pool'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

