server:
  port: 8000


spring:
  application:
    name: DDDSample
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    max-active: '10 # Maximum number of connections allowed in the pool'
    pool-size: '5  # Minimum number of idle connections in the pool'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  redis:
    host: localhost
    port: 6379
    password: '12345abcd;;'
    database: 0

  security:
    user:
      name: 'user'
      password: 'password'
